package br.com.easy_inventory.management.audit.entity;

public enum AuditAction {
    USER_CREATED, USER_UPDATED, USER_DEACTIVATED, USER_ROLE_CHANGED,
    UNIT_CREATED, UNIT_UPDATED, UNIT_DEACTIVATED,
    INGREDIENT_CREATED, INGREDIENT_UPDATED, INGREDIENT_MIN_UPDATED, INGREDIENT_DEACTIVATED,
    PRODUCT_CREATED, PRODUCT_UPDATED, PRODUCT_PRICE_CHANGED, PRODUCT_RECIPE_CHANGED, PRODUCT_DEACTIVATED,
    STOCK_ENTRY, STOCK_EXIT, STOCK_ADJUSTMENT,
    PURCHASE_ORDER_CREATED, PURCHASE_ORDER_RECEIVED, PURCHASE_ORDER_CANCELED,
    ORDER_CREATED, ORDER_UPDATED, ORDER_STARTED, ORDER_COMPLETED, ORDER_CANCELED
}
